#!/usr/bin/env bash
# Automating script running

sudo apt-get update -y
sudo apt-get upgrade -y

sudo apt-get install nginx -y

sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i 's/default_server//g' /etc/nginx/sites-available/default

sudo service nginx restart
