#!/usr/bin/env bash
# Automating script running

apt-get update
apt-get install nginx -y
service nginx start
echo "Hello World!" > /var/www/html/index.html
sudo sed -i 's/default_server//g' /etc/nginx/sites-available/default
service nginx reload
