#!/usr/bin/env bash
# Install nginx web server on the server
apt-get update
apt-get install nginx -y

echo "Heloo World!" > /var/www/html/index.html
printf %s "server {
     listen 	 80 default_server;
     listed 	 [::]:80 default_server;
     root	 /var/www/html;
     index 	 index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default
systemctl nginx restart
