#!/usr/bin/env bash
# Redirecting to another page by first installing nginx
apt-get update
apt-get install nginx -y
echo "Helo World" > /var/www/html/index.html

printf %s "server {
     listen 	 80 default_server;
     listen 	 [::]:80 default_server;
     root 	 /var/www/html;
     index	 index.html index.htm;

     location /redirect_me {
        return 301 https://www.zakisu.vercel.app;
     }
}
" > /etc/nginx/sites-available/default
systemctl nginx restart
