#!/usr/bin/env bash
# Update package lists, install Nginx and redirect to youtube channel

sudo apt-get update
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name 54.82.180.5;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    root /var/www/html;
    index index.html index.htm;
}
EOF

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

sudo systemctl reload nginx
