#!/usr/bin/env bash
# This Bash script automatically configures a new Ubuntu machine

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx

sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx

echo "Hello World!" > /var/www/html/index.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=hAwpj1ZHHtY;"

sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
