#!/usr/bin/env bash
# Redirecting to another page by first installing nginx
apt-get update
apt-get install nginx -y
echo "Helo World" > /var/www/html/index.html

touch /var/www/html/pagenotfound.html
echo "Ceci n'est pas une page" > /var/www/html/pagenotfound.html

printf %s "server {
     listen 	 80 default_server;
     listen 	 [::]:80 default_server;
     root 	 /var/www/html;
     index	 index.html index.htm;

     location /redirect_me {
        return 301 https://www.zakisu.vercel.app;
     }

     error_page 404 /pagenotfound.html;
     location /pagenotfound {
       root /var/www/html;
       internal
}
" > /etc/nginx/sites-available/default
systemctl nginx restart
