#!/usr/bin/env bash
# Manging manage_process
file=/var/run/my_process.pid
if [ "$1" = "start" ]
then
	./manage_my_process &
	echo $! >> $file
	echo "manage_my_process started"
elif [ "$1" =  "stop" ]
then
	xargs kill < "$file"
	rm ./my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
	xargs kill < "$file"
	rm $file
	./manage_my_process &
	echo $! >> $file
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
