#!/usr/bin/env bash
# Bad luck for 4th iter Good luck for 8th iter
str="Best School"
i=1
while (( i < 11 )); do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "$str"
	fi
	((i++))
done
